"""Added booking model

Revision ID: fbf5112a6cfe
Revises: c9454ba56457
Create Date: 2025-05-06 06:53:50.310652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbf5112a6cfe'
down_revision = 'c9454ba56457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_no', sa.String(), nullable=False),
    sa.Column('occasion', sa.String(), nullable=True),
    sa.Column('dishes', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('message', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('_alembic_tmp_contact')
    with op.batch_alter_table('testimonial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))
        batch_op.drop_column('Description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Description', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('description')

    op.create_table('_alembic_tmp_contact',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('enquiry', sa.VARCHAR(length=500), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('phone_number', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('booking')
    # ### end Alembic commands ###
